name: tests
description: A new Flutter application.
publish_to: none

version: 1.0.0+1
homepage: https://github.com/droididan/dart_extentions
environment:
  sdk: ">=2.17.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter

  dart_extensions:
    path: ../

  cupertino_icons: ^1.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
